mosaique/admincos/urls.py
from django.urls import path
from . import views

app_name='admincos'

urlpatterns = [
    path('controle-panel', views.controlepanel, name='controlepanel'),


    #################################################################################
    ##################################   order  #####################################
    #################################################################################
    path('orders/list', views.list_orders, name='list_orders'),
    path('orders/archived/list', views.archived_commandes, name='archived_commandes'),
    path('order/one/<int:number>/show', views.one_order, name='one_order'),
    path('order/one/<int:number>/edit', views.edit_order, name='edit_order'),
    path('order/one/<int:number>/set-visibilty/<str:vis>', views.change_visibilty, name='change_visibilty'),




    #################################################################################
    ################################   supplier  ####################################
    #################################################################################
    path('supplier/create', views.create_supplier, name="create_supplier"),
    path('supplier/list', views.list_supplier, name='list_supplier'),
    path('supplier/<slug:slug>/show', views.one_supplier, name="one_supplier"),





    #################################################################################
    ################################   category  ####################################
    #################################################################################
    path('category/create', views.create_category, name="create_category"),
    path('category/list', views.list_categories, name='list_categories'),
    path('category/<slug:slug>/show', views.one_category, name="one_category"),




    #################################################################################
    #################################   product  ####################################
    #################################################################################
    path('product/create', views.create_product, name="create_product"),
    path('product/<slug:slug>/update', views.update_product, name="update_product"),
    path('products/list', views.products_list, name='products_list'),
    path('product/<slug:slug>/show', views.one_produit, name="one_produit"),
    path('product/<slug:slug>/delete', views.delete_produit, name="delete_produit"),
    path('products/archived/list', views.archived_products, name='archived_products'),

]

mosaique/carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
]

mosaique/mosaique/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from admincos.views import deneratePdf

urlpatterns = [
    path('securelogin/', admin.site.urls),
    path('', views.home, name="home"),
    path('deneratePdf', deneratePdf, name="deneratePdf"),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin-cos/', include('admincos.urls')),
    path('supplier/', include('supplier.urls')),
    path('category/', include('category.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mosaique/orders/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('place_order/', views.place_order, name="place_order"),
    path('payments/', views.payments, name="payments"),
    path('order_complete/', views.order_complete, name="order_complete"),
]

mosaique/orders/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'phone_number', 'email_address', 'address_line_1', 'country', 'city', 'postal_code', 'order_note', 'date_recovery', 'time_recovery') 

mosaique/admincos/views.py
import datetime
from django.contrib import messages
from django.shortcuts import redirect, render
from supplier.models import Supplier
from category.models import Category
from store.models import Product
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from orders.models import Order, OrderProduct
from .context_processors import getters




@login_required(login_url='login')
def controlepanel(request):
    orders = Order.objects.filter(is_active=True).all()
    return render(request, 'admincos/controlepanel.html', {"orders" : orders})

@login_required(login_url='login')
def archived_commandes(request):
    orders = Order.objects.filter(is_active=False).all()
    return render(request, 'admincos/controlepanel.html', {"orders" : orders})

@login_required(login_url='login')
def list_orders(request):
    return redirect('admincos:controlepanel')

@login_required(login_url='login')
def one_order(request, number):
    order = Order.objects.filter(order_number=number).first()
    if not request.user.is_superuser or not order:
        return redirect(request.META.get('HTTP_REFERER'))
    order.items = OrderProduct.objects.filter(order = order).all()
    return render(request, 'admincos/show/order.html', {"order":order})

@login_required(login_url='login')
def change_visibilty(request, number, vis):
    order = Order.objects.filter(order_number=number).first()
    if not request.user.is_superuser or not order or vis not in ['True', 'False']:
        return redirect(request.META.get('HTTP_REFERER'))
    res = True if vis=='True' else False
    order.is_active = res
    order.save()
    return render(request, 'admincos/show/order.html', {"order":order})


@login_required(login_url='login')
def edit_order(request, number):
    res = {
            1: 'Nouvelle commande',
            2: 'En cours de traitement',
            3: 'Commande prête',
            4: 'Commande récupéré',
            5: 'Commande annulée',
                }
    order = Order.objects.filter(order_number=number).first()
    if not request.user.is_superuser or not order:
        return redirect(request.META.get('HTTP_REFERER'))
    if request.method == 'POST':
        order.status = res[int(request.POST.get('new-order-status'))]
        order.save()

    return redirect('admincos:one_order', order.order_number)


@login_required(login_url='login')
def list_supplier(request):
    suppliers = Supplier.objects.all()
    return render(request, 'admincos/list/supplier.html', {"suppliers": suppliers})



@login_required(login_url='login')
def products_list(request):
    # categories = Category.objects.all()
    products = Product.objects.all()
    return render(request, 'admincos/list/products.html', {"products": products})


@login_required(login_url='login')
def archived_products(request):
    products = Product.objects.filter(is_available=False).all()
    return render(request, 'admincos/list/products.html', {"products": products})



@login_required(login_url='login')
def create_product(request):
    if not request.user.is_superuser:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))
    if request.method == 'POST':
        product_name = request.POST.get('product_name')
        description = request.POST.get('description')
        price = request.POST.get('price')
        stock = request.POST.get('stock')
        category_id = request.POST.get('category')
        supplier_id = request.POST.get('supplier')
        category = Category.objects.filter(id = category_id).first()
        supplier = Supplier.objects.filter(id = supplier_id).first()
        if not category or not supplier:
            messages.success(request, 'Opps :>')
            return redirect(request.META.get('HTTP_REFERER'))
        product = Product.objects.create(
            product_name = product_name,
            description = description,
            price = price,
            stock = stock,
            category = category,
            supplier = supplier,
        )
        if request.FILES.get('product_image'):
            img = request.FILES.get('product_image')
            product.images = img
            product.save()
        # return redirect(request.META.get('HTTP_REFERER'))
        return redirect('admincos:one_produit', product.slug)

    return render(request, 'admincos/create/product.html')

@login_required(login_url='login')
def one_produit(request, slug):
    product = Product.objects.filter(slug = slug).first()
    if not request.user.is_superuser or not product:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))

        # return redirect(request.META.get('HTTP_REFERER'))
    return render(request, 'admincos/show/product_detail_admin.html', {'single_product': product})


@login_required(login_url='login')
def delete_produit(request, slug):
    product = Product.objects.filter(slug = slug).first()
    if not request.user.is_superuser or not product:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))
    product.delete()
    return redirect('admincos:products_list')


@login_required(login_url='login')
def update_product(request, slug):
    product = Product.objects.filter(slug = slug).first()
    if not request.user.is_superuser or not product:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))
    if request.method == 'POST':
        product_name = request.POST.get('product_name')
        description = request.POST.get('description')
        price = request.POST.get('price')
        stock = request.POST.get('stock')
        category_id = request.POST.get('category')
        supplier_id = request.POST.get('supplier')
        category = Category.objects.filter(id = category_id).first()
        supplier = Supplier.objects.filter(id = supplier_id).first()
        if not category or not supplier:
            messages.success(request, 'Opps :>')
            return redirect(request.META.get('HTTP_REFERER'))

        product.product_name = product_name
        product.description = description
        product.price = price
        product.stock = stock
        product.category = category
        product.supplier = supplier

        if request.FILES.get('product_image'):
            img = request.FILES.get('product_image')
            product.images = img

        product.save()
        return redirect('admincos:one_produit', product.slug)
    return render(request, 'admincos/update/product.html', {"product":product})




@login_required(login_url='login')
def create_supplier(request):
    if not request.user.is_superuser:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        email = request.POST.get('email')

        supplier = Supplier.objects.create(
            name = name,
            phone = phone,
            email = email,
        )
        return redirect('admincos:one_supplier', supplier.slug)
    return render(request, 'admincos/create/supplier.html')

@login_required(login_url='login')
def one_supplier(request, slug):
    supplier = Supplier.objects.filter(slug = slug).first()
    if not request.user.is_superuser or not supplier:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))
    products = Product.objects.filter(supplier = supplier).all()
    return render(request, 'supplier/show.html', {'supplier': supplier, 'products':products})




#################################################################################
################################   category  ####################################
#################################################################################

@login_required(login_url='login')
def list_categories(request):
    categories = Category.objects.annotate(num_products=Count('product'))
    return render(request, 'admincos/list/categories.html', {"categories": categories})

@login_required(login_url='login')
def create_category(request):
    if not request.user.is_superuser:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))
    if request.method == 'POST':
        category_name = request.POST.get('category_name')
        description = request.POST.get('category_description')

        category = Category.objects.create(
            category_name = category_name,
            description = description,
        )
        if request.FILES.get('category_image'):
            img = request.FILES.get('category_image')
            category.cat_image = img
            category.save()
        messages.success(request, 'La catégorie a été créée avec succès')
        return redirect('admincos:one_category', category.slug)
    return render(request, 'admincos/create/category.html')

@login_required(login_url='login')
def one_category(request, slug):
    category = Category.objects.filter(slug = slug).first()
    if not request.user.is_superuser or not category:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))
    # get nb produit for this category
    products = Product.objects.filter(category = category).all()
    return render(request, 'category/show.html', {'category': category, 'products':products})



from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template

from xhtml2pdf import pisa

def render_to_pdf(template_src, context_dict={}):
    template = get_template(template_src)
    html  = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return None

mosaique/templates/admincos/show/order.html
{% extends '../../base.html' %}

{% load static %}

<link href="{% static 'assets/gm.css' %}" rel="stylesheet"/>
{% block titre %}Controle panel{% endblock titre %}

{% block main %}


<style>
    .text-gray {
        color: gray;
    }
</style>

<main class="container">
    <div class="d-flex justify-content-between align-content-center align-items-center px-5 my-1 border-bottom border-3 ">
        <h3 class="text-center text-dark">Commande : {{ order.order_number }}</h3>
        <button type="button" data-modal-targget="modal-update-order" onclick="open_close_GM_costum_modal(this)" class="normal-btn bg-success text-white px-2 py-1 rounded"><i class="fa-solid fa-pen-to-square"></i></button>
    </div>
    <!--  -->
    <div class="row">
        <div class="col-lg-4">
            <div class="card">
                <div class="card-body">
                    <h5>Informations de la commande</h5>
                    <div class="d-flex flex-column justify-content-start align-content-center">
                        <span style="font-weight: bold;">N° de la commande</span>
                        <span class="text-gray pl-2">{{ order.order_number }}</span>
                    </div>
                    <div class="d-flex flex-column justify-content-start align-content-center">
                        <span style="font-weight: bold;">Faite le :</span>
                        <span class="text-gray pl-2">{{ order.created_at }}<br>Donc il y a {{order.created_at|timesince}}</span>
                    </div>
                    <div class="d-flex flex-column justify-content-start align-content-center">
                        <span style="font-weight: bold;">Dernière modification :</span>
                        <span class="text-gray pl-2">{{ order.updated_at }}<br>Donc il y a {{order.updated_at|timesince}}</span>
                    </div>
                    <div class="d-flex flex-column justify-content-start align-content-center">
                        <span style="font-weight: bold;">Temps de la récupération :</span>
                        <span class="text-gray pl-2">{{ order.get_recovery_datetime }}</span>
                    </div>
                    <div class="d-flex flex-column justify-content-start align-content-center">
                        <span style="font-weight: bold;">Visiblité :</span>
                        <span class="text-gray pl-2">{{ order.get_visibilty }}</span>
                    </div>
                    <div class="d-flex flex-column justify-content-start align-content-center">
                        <span style="font-weight: bold;">Statut actuel :</span>
                        <span class="text-{{order.get_status_color}} pl-2">{{ order.status }}</span>
                    </div>
                    <hr>
                    <h5>Informations du client</h5>
                    <div class="d-flex flex-column justify-content-start align-content-center">
                        <span style="font-weight: bold;">Nom complet :</span>
                        <span class="text-gray pl-2">{{ order.user.full_name }}</span>
                    </div>
                    <div class="d-flex flex-column justify-content-start align-content-center">
                        <span style="font-weight: bold;">Adresse mail :</span>
                        <span class="text-gray pl-2">{{ order.user.email_address }}</span>
                    </div>
                    <div class="d-flex flex-column justify-content-start align-content-center">
                        <span style="font-weight: bold;">N° de téléphone :</span>
                        <span class="text-gray pl-2">{{ order.user.set_phone_number_format }}</span>
                    </div>
                    <div class="d-flex flex-column justify-content-start align-content-center">
                        <span style="font-weight: bold;">Adresse :</span>
                        <span class="text-gray pl-2">{{ order.get_address }}</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="crad">
                <div class="card-body">
                    <h5>Produits de la commande</h5>
                    <div class="table-responsive">
                        <table class="table table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th>Produit</th>
                                    <th>Quantité</th>
                                    <th>Prix</th>
                                    <th>Prix total</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in order.items.all %}
                                    <tr>
                                        <td>
                                            <a href="{{ item.product.get_url }}">{{ item.product.product_name }}</a>
                                        </td>
                                        <td>{{ item.quantity }}</td>
                                        <td>{{ item.product.price }} €</td>
                                        <td>{{ item.get_total_price }} €</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>


    </div>

    <div class="mg-costum-modal-holder">
        <div id="modal-update-order" class="mg-costum-modal">
            <div class="mg-costum-modal-header">
                <div class="mg-costum-modal-header-content">Modificatrion d'une commande</div>
                <span id="mg-costum-modal-close-span" onclick="close_GM_modal_btns(this)" class="mg-costum-modal-header-close">&times;</span>
            </div>
            <div class="mg-costum-modal-body">
                <form action="{% url 'admincos:edit_order' order.order_number %}" method="POST">
                    {% csrf_token %}
                    <div class="d-flex flex-column justify-content-start gap-1 mb-2">
                        <label for="new-order-status">La statut de la commande</label>
                        <select name="new-order-status" id="new-order-status" class="form-control form-select">
                            {% for id, status in get_all_order_status.items %}
                                <option value="{{ id }}" {% if order.get_status == status %}selected{% endif %}>{{ status }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="btns mt-3">
                        {% if order.is_active %}
                        <a href="{% url 'admincos:change_visibilty' order.order_number False %}" class="normal-link px-3 py-2 rounded text-white bg-danger">Archiver</a>
                        {% else %}
                        <a href="{% url 'admincos:change_visibilty' order.order_number True %}" class="normal-link px-3 py-2 rounded text-white bg-success">Désarchiver</a>
                        {% endif %}
                    </div>
                </form>
            </div>
            <div class="mg-costum-modal-footer">
                <button class="mg-costum-modal-footer-btn" onclick="close_GM_modal_btns(this)" id="mg-costum-modal-footer-btn-close">Annuler</button>
                <button type="submit" class="mg-costum-modal-footer-btn" onclick="submitForm(this)"  id="mg-costum-modal-footer-btn-go">Modifier</button>
            </div>
        </div>
    </div>

</main>

{% endblock main %}

mosaique/templates/admincos/show/product_detail_admin.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Produit{% endblock %}

{% block main %}

<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
<article class="gallery-wrap">
	<div class="img-big-wrap">
	   <a href="#">{% if single_product.images %}<img src="{{ single_product.images.url }}">{% endif %}</a>
	</div> <!-- img-big-wrap.// -->

</article> <!-- gallery-wrap .end// -->
		</aside>
		<main class="col-md-6 border-left">
<article class="content-body">

<h2 class="title">{{ single_product.product_name }}</h2>

<div class="rating-star">
	<span>
		<i class="fa fa-star{% if single_product.averageRaview < 0.5 %}-o{% elif single_product.averageRaview >= 0.5 and single_product.averageRaview < 1 %}-half-o{% endif%}" aria-hidden="true"></i>
		<i class="fa fa-star{% if single_product.averageRaview < 1.5 %}-o{% elif single_product.averageRaview >= 1.5 and single_product.averageRaview < 2 %}-half-o{% endif%}" aria-hidden="true"></i>
		<i class="fa fa-star{% if single_product.averageRaview < 2.5 %}-o{% elif single_product.averageRaview >= 2.5 and single_product.averageRaview < 3 %}-half-o{% endif%}" aria-hidden="true"></i>
		<i class="fa fa-star{% if single_product.averageRaview < 3.5 %}-o{% elif single_product.averageRaview >= 3.5 and single_product.averageRaview < 4 %}-half-o{% endif%}" aria-hidden="true"></i>
		<i class="fa fa-star{% if single_product.averageRaview < 4.5 %}-o{% elif single_product.averageRaview >= 4.5 and single_product.averageRaview < 5 %}-half-o{% endif%}" aria-hidden="true"></i>
		{{ single_product.averageRaview }}
	</span>
</div>
<span>{{ single_product.countRaview }} Reviews</span>


<div class="mb-3">
	<var class="price h4">€ {{ single_product.price }}</var>
</div>
<hr>
<h6>Description</h6>
<p>{{ single_product.description }}</p>


	<!-- <hr>
	<div class="row">
		<div class="item-option-select">
			<h6>Choose Color</h6>
			<div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
			  <label class="btn btn-light">
			    <input type="radio" name="radio_color"> Silver
			  </label>
			  <label class="btn btn-light">
			    <input type="radio" name="radio_color" > Gray
			  </label>
			  <label class="btn btn-light active">
			    <input type="radio" name="radio_color checked"> Gold
			  </label>
			  <label class="btn btn-light">
			    <input type="radio" name="radio_color"> Black
			  </label>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="item-option-select">
			<h6>Select Size</h6>
			<div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
			  <label class="btn btn-light">
			    <input type="radio" name="radio_color"> S
			  </label>
			  <label class="btn btn-light active">
			    <input type="radio" name="radio_color" checked> M
			  </label>
			  <label class="btn btn-light">
			    <input type="radio" name="radio_color"> L
			  </label>
			  <label class="btn btn-light">
			    <input type="radio" name="radio_color"> XL
			  </label>
			</div>
		</div>
	</div> -->
	<hr>


	<div class="row">
		<div class="w-100 d-flex justify-content-center align-items-center gap-5">
			{% if single_product.stock <= 0 %}
		<h5 class="text-danger">Out of stock</h5>
    {% else %}
		{% if in_cart %}
			<a href="#" class="btn  btn-success"> <span class="text">Added to cart</span> <i class="fas fa-check"></i>  </a>
			<a href="{% url 'cart' %}" class="btn  btn-primary"> <span class="text">View Cart</span> <i class="fas fa-eye"></i>  </a>
		{% else %}
			<a href="{% url 'add_cart' single_product.id %}" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </a>
		{% endif %}
	{% endif %}
			{% if request.user.is_superuser %}
				<a href="{% url 'admincos:update_product' single_product.slug %}" class="normal-link bg-success text-white px-3 py-2 rounded border ml-3">
					<i class="fa-solid fa-pen-to-square"></i>
				</a>
				<button type="button" data-modal-targget="modal-delete-prod" onclick="open_close_GM_costum_modal(this)"  class="normal-link bg-danger  text-white px-3 py-2 rounded border ml-3">
					<i class="fa-solid fa-trash"></i>
				</button>

			{% endif %}
		</div>
	</div>
	<hr>

</article> <!-- product-info-aside .// -->
		</main> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<br>

<div class="row">
			<div class="col-md-9">



				


	<header class="section-heading">
		<h3>Avis des clients </h3>

	</header>
{% for review in reviews %}
	<article class="box mb-3">
		<div class="icontext w-100">
			<div class="text">
				<span class="date text-muted float-md-right">{{ review.created_date }}</span>
				<h5 class="mb-1">{{ review.user.full_name }}</h5>

			</div>
		</div> <!-- icontext.// -->
		<div class="mt-3">
			<h6>{{ review.subject }}</h6>
			<div class="rating-star">
				<span>
					<i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
				</span>
			</div>
			<p>
				{{ review.review }}
			</p>
		</div>
	</article>
{% endfor %}



	</div> <!-- col.// -->
</div> <!-- row.// -->


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

<div class="mg-costum-modal-holder">
	<div id="modal-delete-prod" class="mg-costum-modal">
		<div class="mg-costum-modal-header">
			<div class="mg-costum-modal-header-content">Supprission d'un fournisseurs</div>
			<span id="mg-costum-modal-close-span" onclick="close_GM_modal_btns(this)" class="mg-costum-modal-header-close">&times;</span>
		</div>
		<div class="mg-costum-modal-body">
			Vous voulez supprimer <span class="text-danger">{{ single_product.product_name }}</span> ?
		</div>
		<div class="mg-costum-modal-footer">
			<button class="mg-costum-modal-footer-btn" onclick="close_GM_modal_btns(this)" id="mg-costum-modal-footer-btn-close">Annuler</button>
			<button class="mg-costum-modal-footer-btn" id="mg-costum-modal-footer-btn-go">
				<a href="{% url 'admincos:delete_produit' single_product.slug %}" class="text-white">Supprimer</a>
			</button>
		</div>
	</div>

</div>
{% endblock main %}