mosaique/admincos/urls.py
from django.urls import path
from . import views

app_name='admincos'

urlpatterns = [
    path('controle-panel', views.controlepanel, name='controlepanel'),


    #################################################################################
    ##################################   order  #####################################
    #################################################################################
    path('orders/list', views.list_orders, name='list_orders'),
    path('orders/archived/list', views.archived_commandes, name='archived_commandes'),
    path('order/one/<int:number>/show', views.one_order, name='one_order'),
    path('order/one/<int:number>/edit', views.edit_order, name='edit_order'),
    path('order/one/<int:number>/set-visibilty/<str:vis>', views.change_visibilty, name='change_visibilty'),




    #################################################################################
    ################################   supplier  ####################################
    #################################################################################
    path('supplier/create', views.create_supplier, name="create_supplier"),
    path('supplier/list', views.list_supplier, name='list_supplier'),
    path('supplier/<slug:slug>/show', views.one_supplier, name="one_supplier"),





    #################################################################################
    ################################   category  ####################################
    #################################################################################
    path('category/create', views.create_category, name="create_category"),
    path('category/list', views.list_categories, name='list_categories'),
    path('category/<slug:slug>/show', views.one_category, name="one_category"),




    #################################################################################
    #################################   product  ####################################
    #################################################################################
    path('product/create', views.create_product, name="create_product"),
    path('product/<slug:slug>/update', views.update_product, name="update_product"),
    path('products/list', views.products_list, name='products_list'),
    path('product/<slug:slug>/show', views.one_produit, name="one_produit"),
    path('product/<slug:slug>/delete', views.delete_produit, name="delete_produit"),
    path('products/archived/list', views.archived_products, name='archived_products'),

]

mosaique/carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
]

mosaique/category/urls.py
from django.urls import path
from . import views

app_name='category'

urlpatterns = [
    path('create', views.create, name='create'),
    path('<slug:slug>/delete', views.delete, name='delete'),
    path('<slug:slug>/update', views.update, name='update'),
    path('<slug:slug>/show', views.show, name='show'),
    path('<slug:slug>/list/products', views.list_products, name='list_products'),
    path('add/products', views.add_products, name='add_products'),
    path('delete/products/<slug:prod>', views.delete_products, name='delete_products'),
    path('update/products/<slug:prod>', views.update_prod, name='update_prod'),
]

mosaique/mosaique/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from admincos.views import deneratePdf

urlpatterns = [
    path('securelogin/', admin.site.urls),
    path('', views.home, name="home"),
    path('deneratePdf', deneratePdf, name="deneratePdf"),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin-cos/', include('admincos.urls')),
    path('supplier/', include('supplier.urls')),
    path('category/', include('category.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mosaique/admincos/views.py
import datetime
from django.contrib import messages
from django.shortcuts import redirect, render
from supplier.models import Supplier
from category.models import Category
from store.models import Product
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from orders.models import Order, OrderProduct
from .context_processors import getters




@login_required(login_url='login')
def controlepanel(request):
    orders = Order.objects.filter(is_active=True).all()
    return render(request, 'admincos/controlepanel.html', {"orders" : orders})

@login_required(login_url='login')
def archived_commandes(request):
    orders = Order.objects.filter(is_active=False).all()
    return render(request, 'admincos/controlepanel.html', {"orders" : orders})

@login_required(login_url='login')
def list_orders(request):
    return redirect('admincos:controlepanel')

@login_required(login_url='login')
def one_order(request, number):
    order = Order.objects.filter(order_number=number).first()
    if not request.user.is_superuser or not order:
        return redirect(request.META.get('HTTP_REFERER'))
    order.items = OrderProduct.objects.filter(order = order).all()
    return render(request, 'admincos/show/order.html', {"order":order})

@login_required(login_url='login')
def change_visibilty(request, number, vis):
    order = Order.objects.filter(order_number=number).first()
    if not request.user.is_superuser or not order or vis not in ['True', 'False']:
        return redirect(request.META.get('HTTP_REFERER'))
    res = True if vis=='True' else False
    order.is_active = res
    order.save()
    return render(request, 'admincos/show/order.html', {"order":order})


@login_required(login_url='login')
def edit_order(request, number):
    res = {
            1: 'Nouvelle commande',
            2: 'En cours de traitement',
            3: 'Commande prête',
            4: 'Commande récupéré',
            5: 'Commande annulée',
                }
    order = Order.objects.filter(order_number=number).first()
    if not request.user.is_superuser or not order:
        return redirect(request.META.get('HTTP_REFERER'))
    if request.method == 'POST':
        order.status = res[int(request.POST.get('new-order-status'))]
        order.save()

    return redirect('admincos:one_order', order.order_number)


@login_required(login_url='login')
def list_supplier(request):
    suppliers = Supplier.objects.all()
    return render(request, 'admincos/list/supplier.html', {"suppliers": suppliers})



@login_required(login_url='login')
def products_list(request):
    # categories = Category.objects.all()
    products = Product.objects.all()
    return render(request, 'admincos/list/products.html', {"products": products})


@login_required(login_url='login')
def archived_products(request):
    products = Product.objects.filter(is_available=False).all()
    return render(request, 'admincos/list/products.html', {"products": products})



@login_required(login_url='login')
def create_product(request):
    if not request.user.is_superuser:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))
    if request.method == 'POST':
        product_name = request.POST.get('product_name')
        description = request.POST.get('description')
        price = request.POST.get('price')
        stock = request.POST.get('stock')
        category_id = request.POST.get('category')
        supplier_id = request.POST.get('supplier')
        category = Category.objects.filter(id = category_id).first()
        supplier = Supplier.objects.filter(id = supplier_id).first()
        if not category or not supplier:
            messages.success(request, 'Opps :>')
            return redirect(request.META.get('HTTP_REFERER'))
        product = Product.objects.create(
            product_name = product_name,
            description = description,
            price = price,
            stock = stock,
            category = category,
            supplier = supplier,
        )
        if request.FILES.get('product_image'):
            img = request.FILES.get('product_image')
            product.images = img
            product.save()
        # return redirect(request.META.get('HTTP_REFERER'))
        return redirect('admincos:one_produit', product.slug)

    return render(request, 'admincos/create/product.html')

@login_required(login_url='login')
def one_produit(request, slug):
    product = Product.objects.filter(slug = slug).first()
    if not request.user.is_superuser or not product:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))

        # return redirect(request.META.get('HTTP_REFERER'))
    return render(request, 'admincos/show/product_detail_admin.html', {'single_product': product})


@login_required(login_url='login')
def delete_produit(request, slug):
    product = Product.objects.filter(slug = slug).first()
    if not request.user.is_superuser or not product:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))
    product.delete()
    return redirect('admincos:products_list')


@login_required(login_url='login')
def update_product(request, slug):
    product = Product.objects.filter(slug = slug).first()
    if not request.user.is_superuser or not product:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))
    if request.method == 'POST':
        product_name = request.POST.get('product_name')
        description = request.POST.get('description')
        price = request.POST.get('price')
        stock = request.POST.get('stock')
        category_id = request.POST.get('category')
        supplier_id = request.POST.get('supplier')
        category = Category.objects.filter(id = category_id).first()
        supplier = Supplier.objects.filter(id = supplier_id).first()
        if not category or not supplier:
            messages.success(request, 'Opps :>')
            return redirect(request.META.get('HTTP_REFERER'))

        product.product_name = product_name
        product.description = description
        product.price = price
        product.stock = stock
        product.category = category
        product.supplier = supplier

        if request.FILES.get('product_image'):
            img = request.FILES.get('product_image')
            product.images = img

        product.save()
        return redirect('admincos:one_produit', product.slug)
    return render(request, 'admincos/update/product.html', {"product":product})




@login_required(login_url='login')
def create_supplier(request):
    if not request.user.is_superuser:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        email = request.POST.get('email')

        supplier = Supplier.objects.create(
            name = name,
            phone = phone,
            email = email,
        )
        return redirect('admincos:one_supplier', supplier.slug)
    return render(request, 'admincos/create/supplier.html')

@login_required(login_url='login')
def one_supplier(request, slug):
    supplier = Supplier.objects.filter(slug = slug).first()
    if not request.user.is_superuser or not supplier:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))
    products = Product.objects.filter(supplier = supplier).all()
    return render(request, 'supplier/show.html', {'supplier': supplier, 'products':products})




#################################################################################
################################   category  ####################################
#################################################################################

@login_required(login_url='login')
def list_categories(request):
    categories = Category.objects.annotate(num_products=Count('product'))
    return render(request, 'admincos/list/categories.html', {"categories": categories})

@login_required(login_url='login')
def create_category(request):
    if not request.user.is_superuser:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))
    if request.method == 'POST':
        category_name = request.POST.get('category_name')
        description = request.POST.get('category_description')

        category = Category.objects.create(
            category_name = category_name,
            description = description,
        )
        if request.FILES.get('category_image'):
            img = request.FILES.get('category_image')
            category.cat_image = img
            category.save()
        messages.success(request, 'La catégorie a été créée avec succès')
        return redirect('admincos:one_category', category.slug)
    return render(request, 'admincos/create/category.html')

@login_required(login_url='login')
def one_category(request, slug):
    category = Category.objects.filter(slug = slug).first()
    if not request.user.is_superuser or not category:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))
    # get nb produit for this category
    products = Product.objects.filter(category = category).all()
    return render(request, 'category/show.html', {'category': category, 'products':products})



from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template

from xhtml2pdf import pisa

def render_to_pdf(template_src, context_dict={}):
    template = get_template(template_src)
    html  = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return None

mosaique/supplier/views.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from .models import Supplier
from store.models import Product
from django.contrib.auth.decorators import login_required


@login_required(login_url='login')
def create(request):
    if not request.user.is_superuser:
        messages.success(request, 'Opps :>')
        return redirect('login')
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        supplier = Supplier.objects.create(name = name, phone = phone, email = email)
        messages.success(request, 'Votre fournisseur a été créé avec succès')
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect(request.META.get('HTTP_REFERER'))


@login_required(login_url='login')
def update(request, slug):
    print('sliug', slug)
    supplier = Supplier.objects.filter(slug = slug).first()
    print('supplier', supplier)
    if not request.user.is_superuser or not supplier:
        print('here 1')
        messages.success(request, 'Opps :>')
        return redirect('login')
    if request.method == 'POST':
        print('here 2')
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        supplier.name = name
        supplier.email = email
        supplier.phone = phone
        supplier.save()
        messages.success(request, 'Votre fournisseur a été modifié avec succès')
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect(request.META.get('HTTP_REFERER'))

@login_required(login_url='login')
def delete(request, slug):
    supplier = Supplier.objects.filter(slug = slug).first()
    if not request.user.is_superuser or not delete:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))
    supplier.delete()
    messages.success(request, 'Deleted')
    return redirect(request.META.get('HTTP_REFERER'))

@login_required(login_url='login')
def show(request, slug):
    supplier = Supplier.objects.filter(slug = slug).first()
    if not request.user.is_superuser or not delete:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))
    products = Product.objects.filter(supplier = supplier).all()
    return render(request, 'supplier/show.html', {'supplier':supplier ,'products':products})


@login_required(login_url='login')
def list_products(request, slug):
    supplier = Supplier.objects.filter(slug = slug).first()
    if not request.user.is_superuser or not delete:
        messages.success(request, 'Opps :>')
        return redirect(request.META.get('HTTP_REFERER'))
    products = Product.objects.filter(supplier = supplier).all()
    return render(request, 'admincos/list/products.html', {'supplier':supplier ,'products':products})

mosaique/templates/admincos/create/category.html
{% extends '../../base.html' %}

{% load static %}

<link href="{% static 'assets/gm.css' %}" rel="stylesheet"/>
{% block titre %}Fournisseurs{% endblock titre %}

{% block main %}

<style>
    #lable-image-input {
        font-size: 5rem;
        text-align: center;
        color: #0d6efd;
        cursor: pointer;

    }
    #image-input {
        display: none;
    }

</style>

<main class="container" id="new-product-container" style="min-height: 84dvh;">
    <h3 class="text-center text-dark my-2 mt-3">Ajouter un produit</h3>
    <form action="{% url 'admincos:create_category'  %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="d-flex flex-column justify-content-start gap-1 mb-2">
            <label for="category_name">Nom de la catégorie:</label>
            <input class="form-control" type="text" id="category_name" name="category_name" placeholder="Nom de la catégorie">
        </div>
        <div class="d-flex flex-column justify-content-start gap-1 mb-2">
            <textarea name="category_description" class="form-control" placeholder="Une description de la catégorie"></textarea>
        </div>
        <div class="d-flex flex-column justify-content-start gap-1 mb-2">
            <input type="file" name="category_image" class="text form-control" id="image-input"  accept="image/*" value=" ">
        </div>

        <div class="d-flex flex-column justify-content-start gap-1 mb-2 border px-4 py-2 rounded">
            <label for="image-input" id="lable-image-input" class="fa-solid fa-file-arrow-up"></label>
            <input type="file" name="category_image"  class="text form-control" id="image-input"  accept="image/*" value=" ">
        </div>
        <div id="image-container" class="d-none mb-5">

        </div>

        <div class="w-100 d-flex justify-content-center align-content-center">
            <button type="submit" class="normal-btn border rounded shadow px-4 py-2 mb-4 bg-success text-white fs-4">Ajouter</button>
        </div>
    </form>
</main>
<script src="{% static 'js/costum-script.js' %}" type="text/javascript"></script>
<script>

    addImagesToContainer()
</script>

{% endblock main %}

mosaique/templates/admincos/create/product.html
{% extends '../../base.html' %}

{% load static %}

<link href="{% static 'assets/gm.css' %}" rel="stylesheet"/>
{% block titre %}Fournisseurs{% endblock titre %}

{% block main %}

<style>
    #lable-image-input {
        font-size: 5rem;
        text-align: center;
        color: #0d6efd;
        cursor: pointer;

    }
    #image-input {
        display: none;
    }

</style>

<main class="container" id="new-product-container" style="min-height: 84dvh;">
    <h3 class="text-center text-dark my-2 mt-3">Ajouter un produit</h3>
    <form action="{% url 'admincos:create_product'  %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="d-flex flex-column justify-content-start gap-1 mb-2 border px-4 py-2 rounded">
            <label for="category_name">Nom du produit:</label>
            <input class="form-control" required type="text" id="product_name" name="product_name" placeholder="Nom du produit">
        </div>
        <div class="d-flex flex-column justify-content-start gap-1 mb-2 border px-4 py-2 rounded">
            <label for="description">La description du produit:</label>
            <textarea name="description" required  class="form-control" placeholder="Une description du produit"></textarea>
        </div>
        <div class="d-flex flex-column justify-content-start gap-1 mb-2 border px-4 py-2 rounded">
            <label for="category_name">Prix du prouit:</label>
            <input class="form-control"  required type="text" id="price" name="price" placeholder="Prix du prouit">
        </div>
        <div class="d-flex flex-column justify-content-start gap-1 mb-2 border px-4 py-2 rounded">
            <label for="category_name">Nombre en stock:</label>
            <input class="form-control"  required type="number" id="stock" name="stock" placeholder="Nombre en stock">
        </div>
        <div class="d-flex flex-column justify-content-start gap-1 mb-2 border px-4 py-2 rounded">
            <label for="category_name">catégorie:</label>
            <select name="category" class="form-control form-select" id="category">
                {% for categorie in categories %}
                <option value="{{ categorie.id }}">{{ categorie.category_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="d-flex flex-column justify-content-start gap-1 mb-2 border px-4 py-2 rounded">
            <label for="category_name">Fournisseuse:</label>
            <select name="supplier" class="form-control form-select" id="supplier">
                {% for supplier in suppliers %}
                <option value="{{ supplier.id }}">{{ supplier.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="d-flex flex-column justify-content-start gap-1 mb-2 border px-4 py-2 rounded">
            <label for="image-input" id="lable-image-input" class="fa-solid fa-file-arrow-up"></label>
            <input type="file" name="product_image" required  class="text form-control" id="image-input"  accept="image/*" value=" ">
        </div>
        <div id="image-container" class="d-none mb-5">

        </div>

        <div class="w-100 d-flex justify-content-center align-content-center">
            <button type="submit" class="normal-btn border rounded shadow px-4 py-2 mb-4 bg-success text-white fs-4">Ajouter</button>
        </div>
    </form>
</main>
<script src="{% static 'js/costum-script.js' %}" type="text/javascript"></script>
<script>

    addImagesToContainer()
</script>

{% endblock main %}

mosaique/templates/admincos/create/supplier.html
{% extends '../../base.html' %}

{% load static %}

<link href="{% static 'assets/gm.css' %}" rel="stylesheet"/>
{% block titre %}Fournisseurs{% endblock titre %}

{% block main %}


<main class="container" id="new-supplier-container" style="min-height: 84dvh;">
    <h3 class="text-center text-dark my-2 mt-3">Ajouter un fournisseur</h3>
    <form action="{% url 'admincos:create_supplier'  %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="d-flex flex-column justify-content-start gap-1 mb-2 border px-4 py-2 rounded">
            <label for="name">Nom du fournisseur :</label>
            <input class="form-control" required type="text" id="name" name="name" placeholder="Nom du fournisseur :">
        </div>
        <div class="d-flex flex-column justify-content-start gap-1 mb-2 border px-4 py-2 rounded">
            <label for="email">Email du fournisseur :</label>
            <input class="form-control"  required type="email" id="email" name="email" placeholder="Email du fournisseur :">
        </div>
        <div class="d-flex flex-column justify-content-start gap-1 mb-2 border px-4 py-2 rounded">
            <label for="phone">N° téléphone du fournisseur ::</label>
            <input class="form-control" required type="text" id="phone" name="phone" placeholder="N° téléphone du fournisseur :">
        </div>

        <div class="w-100 d-flex justify-content-center align-content-center">
            <button type="submit" class="normal-btn border rounded shadow px-4 py-2 mb-4 bg-success text-white fs-4">Ajouter</button>
        </div>
    </form>
</main>
<script src="{% static 'js/costum-script.js' %}" type="text/javascript"></script>
<script>

    addImagesToContainer()
</script>

{% endblock main %}